// Users
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';

// Restaurants
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const SET_SELECTED_RESTAURANT = 'SET_SELECTED_RESTAURANT';

// Reviews
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const PUT_REVIEW_SUCCESS = 'PUT_REVIEW_SUCCESS';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';