// Users
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

// Restaurants
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';

// Reviews
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const PUT_REVIEW_SUCCESS = 'PUT_REVIEW_SUCCESS';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';