// Users
export const SET_ACTIVE_USER = 'SET_ACTIVE_USER';

// Restaurants
export const GET_RESTAURANTS_SUCCESS = 'GET_RESTAURANTS_SUCCESS';
export const SET_SELECTED_RESTAURANT = 'SET_SELECTED_RESTAURANT';

// Reviews
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';